name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Tidy dependencies
      run: go mod tidy

    - name: Get version
      id: version
      run: |
        # Generate version based on commit count and short SHA
        VERSION="v$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    - name: Build for Windows
      run: |
        # Build for Windows x64
        GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o windows-config-builder.exe

    - name: Get file hash
      id: hash
      run: |
        HASH=$(sha256sum windows-config-builder.exe | cut -d' ' -f1)
        echo "sha256=$HASH" >> $GITHUB_OUTPUT
        echo "SHA256: $HASH"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: Release ${{ steps.version.outputs.version }}
        body: |
          ## Windows Configuration Builder
          
          Automated Windows development environment setup using winget package manager.
          
          **Requirements**: Windows 10/11 with winget installed
          
          ## Changes
          - Auto-generated release from commit ${{ github.sha }}
          
          ## Installation
          Download the `windows-config-builder.exe` file and run it on your Windows machine.
          
          ## Winget Package
          To submit this to winget, create a manual PR to [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) with the manifest files.
        files: windows-config-builder.exe
        draft: false
        prerelease: false