name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Tidy dependencies
      run: go mod tidy

    - name: Get version
      id: version
      run: |
        # Generate version based on commit count and short SHA
        VERSION="v$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    - name: Build for Windows
      run: |
        # Build for Windows x64
        GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o windows-config-builder.exe

    - name: Get file hash
      id: hash
      run: |
        HASH=$(sha256sum windows-config-builder.exe | cut -d' ' -f1)
        echo "sha256=$HASH" >> $GITHUB_OUTPUT
        echo "SHA256: $HASH"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: Release ${{ steps.version.outputs.version }}
        body: |
          ## Windows Configuration Builder
          
          Automated Windows development environment setup using winget package manager.
          
          **Requirements**: Windows 10/11 with winget installed
          
          ## Changes
          - Auto-generated release from commit ${{ github.sha }}
          
          ## Installation
          
          ### Option 1: Direct Download
          Download the `windows-config-builder.exe` file and run it on your Windows machine.
          
          ### Option 2: Winget (when available)
          ```powershell
          winget install Abelfubu.WindowsConfigBuilder
          ```
        files: windows-config-builder.exe
        draft: false
        prerelease: false

  winget-submission:
    needs: release
    runs-on: windows-latest
    
    steps:
    - name: Get release info
      id: release_info
      shell: pwsh
      run: |
        # Get the latest release info
        $latestRelease = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases/latest"
        $version = $latestRelease.tag_name
        $downloadUrl = $latestRelease.assets[0].browser_download_url
        echo "version=$version" >> $env:GITHUB_OUTPUT
        echo "download_url=$downloadUrl" >> $env:GITHUB_OUTPUT
        Write-Host "Version: $version"
        Write-Host "Download URL: $downloadUrl"

    - name: Install wingetcreate
      shell: pwsh
      run: |
        # Install wingetcreate tool
        Invoke-WebRequest -Uri "https://aka.ms/wingetcreate/latest" -OutFile "wingetcreate.exe"
        
    - name: Create and submit winget package
      shell: pwsh
      env:
        WINGET_TOKEN: ${{ secrets.WINGET_TOKEN }}
      run: |
        $version = "${{ steps.release_info.outputs.version }}"
        $downloadUrl = "${{ steps.release_info.outputs.download_url }}"
        $versionNum = $version -replace '^v', ''  # Remove 'v' prefix
        
        # Create new package submission
        .\wingetcreate.exe new `
          --urls $downloadUrl `
          --version $versionNum `
          --token $env:WINGET_TOKEN `
          --submit `
          Abelfubu.WindowsConfigBuilder
